'use client'

import { useState } from "react"
import Image from "next/image"
import Input from "../ui/Input"
import { useForm } from 'react-hook-form'

interface twoFaProps {
  status: boolean
}




export default function Twofa({ status }: twoFaProps) {
  const [twofaStatus, settwofsStatus] = useState(status)
  const [qrCode, setQrCode] = useState<string | null>(null)
  const { register, handleSubmit, setError, formState: { errors } } = useForm<{ code: string }>()

  const handleStatus = async () => {
    if (!twofaStatus) {
      // activate 2fa
      const response = await fetch('/api/auth/2fa/setup')
      const data = await response.json()
      setQrCode(data.qrCode)

    } else {
      //de activate 2fa
      setQrCode(null)
      //set disable into the dabase
    }

    settwofsStatus(!twofaStatus)
  }

  const checkCode = (code: string) => {
    const response = await fetch('/api/auth/2fa/verify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code: data.code }),
    })
    if (!response.ok) {
      setError("code", { message: "Invalid code, try again" })
    }

  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-row gap-4">
        <h3>2fa status:</h3>
        <button className="cursor-pointer" onClick={handleStatus}>{twofaStatus ? 'Deactivate' : 'Activate'}</button>
      </div>
      {qrCode && (
        <div>
          <p> scan this code with Authinticator App like Google Authinticator</p>
          <Image src={qrCode} alt="Qr Code" width={200} height={200} />
          <form onSubmit={handleSubmit(checkCode)}>
            <Input
              label="activate 2fa"
              name="2fa code"
              id="2fa-code"
              type="text"
              placeholder="enter the code you generated by your authinticator"
              register={register}
            />
            <button type='submit'>Sbmit</button>
          </form>
        </div>
      )}

    </div>
  )
}
