import Input from "../ui/Input"
import { useForm } from 'react-hook-form'


type TfaFormData = { code: string };

interface VerifyTfaProps {
  onSuccess: () => void
}

export default function VerifyTfa({ onSuccess }: VerifyTfaProps) {
  const { register, handleSubmit, setError, formState: { errors } } = useForm<{ code: string }>()


  const checkCode = async ({ code }: { code: string }) => {

    const response = await fetch('/api/auth/2fa/activation', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code }),
    });
    if (!response.ok) {
      const data = await response.json();
      setError("code", { message: data.error });
      return;
    }
    onSuccess();
  };


  return (
    <form onSubmit={handleSubmit(checkCode)}>
      <Input
        label="activate 2fa"
        name="code"
        id="code"
        type="text"
        placeholder="enter the code you generated by your authenticator"
        register={register}
      />
      <button type='submit'>submit</button>
      {errors.code && <p className="text-red-500">{errors.code.message}</p>}          </form>
  )
}
